"""Type stubs for fastapi — covers only the API surface used by minirag."""

from collections.abc import Callable
from contextlib import AbstractAsyncContextManager
from typing import Any

from starlette.types import Scope

class State:
    def __getattr__(self, name: str) -> Any: ...
    def __setattr__(self, name: str, value: Any) -> None: ...

class FastAPI:
    state: State

    def __init__(
        self,
        *,
        lifespan: Callable[["FastAPI"], AbstractAsyncContextManager[None]] | None = ...,
        **kwargs: Any,
    ) -> None: ...
    def add_exception_handler(self, exc_class: type[Exception], handler: Any) -> None: ...
    def include_router(self, router: "APIRouter", **kwargs: Any) -> None: ...
    async def __call__(self, scope: Any, receive: Any, send: Any) -> None: ...

class APIRouter:
    def __init__(self, *, prefix: str = ..., **kwargs: Any) -> None: ...
    def get(self, path: str, **kwargs: Any) -> Callable[..., Any]: ...
    def post(self, path: str, **kwargs: Any) -> Callable[..., Any]: ...
    def delete(self, path: str, **kwargs: Any) -> Callable[..., Any]: ...
    def put(self, path: str, **kwargs: Any) -> Callable[..., Any]: ...

class Request:
    app: FastAPI

    def __init__(self, scope: Scope, **kwargs: Any) -> None: ...
    async def json(self) -> Any: ...

class BackgroundTasks:
    def add_task(self, func: Callable[..., Any], *args: Any, **kwargs: Any) -> None: ...
