"""Type stubs for fastapi.testclient — covers only the API surface used by minirag tests."""

from contextlib import AbstractContextManager
from typing import Any

import httpx
from fastapi import FastAPI

class TestClient:
    def __init__(self, app: FastAPI, **kwargs: Any) -> None: ...
    def get(self, url: str, **kwargs: Any) -> httpx.Response: ...
    def post(self, url: str, **kwargs: Any) -> httpx.Response: ...
    def put(self, url: str, **kwargs: Any) -> httpx.Response: ...
    def delete(self, url: str, **kwargs: Any) -> httpx.Response: ...
    def stream(self, method: str, url: str, **kwargs: Any) -> AbstractContextManager[httpx.Response]: ...
