"""Type stubs for numpy — covers only the API surface used by minirag."""

from types import TracebackType
from typing import Any, BinaryIO, Self

class dtype:
    def __init__(self, kind: Any) -> None: ...

float32: dtype
int64: dtype

class ndarray:
    dtype: dtype
    ndim: int
    shape: tuple[int, ...]
    def __len__(self) -> int: ...
    def tolist(self) -> Any: ...
    def reshape(self, *shape: int) -> ndarray: ...
    def copy(self) -> ndarray: ...
    def astype(self, dtype: Any, copy: bool = ...) -> ndarray: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __truediv__(self, other: Any) -> ndarray: ...
    def __matmul__(self, other: Any) -> ndarray: ...
    def __neg__(self) -> ndarray: ...

def array(obj: Any, dtype: Any = ...) -> ndarray: ...
def fromiter(iterable: Any, dtype: Any, count: int = ...) -> ndarray: ...
def stack(arrays: Any) -> ndarray: ...
def argsort(a: Any, *, kind: str = ...) -> ndarray: ...
def savez_compressed(file: str | BinaryIO, *args: Any, **kwargs: Any) -> None: ...

class NpzFile:
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...
    def __getitem__(self, key: str) -> ndarray: ...

def load(file: str | BinaryIO | Any, *, allow_pickle: bool = ...) -> NpzFile: ...

class linalg:
    @staticmethod
    def norm(x: Any, **kwargs: Any) -> float: ...
