"""Type stubs for numpy — covers only the API surface used by minirag."""

from typing import Any

class dtype:
    def __init__(self, kind: Any) -> None: ...

float32: dtype
int64: dtype

class ndarray:
    def tolist(self) -> Any: ...
    def reshape(self, *shape: int) -> ndarray: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __truediv__(self, other: Any) -> ndarray: ...

def array(obj: Any, dtype: Any = ...) -> ndarray: ...

class linalg:
    @staticmethod
    def norm(x: Any, **kwargs: Any) -> float: ...
