"""Type stubs for httpx — covers only the API surface used by minirag."""

from collections.abc import Iterator
from types import TracebackType
from typing import Any

class ConnectError(Exception): ...
class ReadTimeout(Exception): ...

class Response:
    status_code: int
    text: str
    headers: dict[str, str]

    def json(self) -> Any: ...
    def iter_lines(self) -> Iterator[str]: ...

class Client:
    def __init__(self, *, base_url: str = ..., timeout: float = ..., **kwargs: Any) -> None: ...
    def __enter__(self) -> Client: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None: ...
    def request(self, *, method: str, url: str, json: Any = ..., **kwargs: Any) -> Response: ...
    def get(self, url: str, **kwargs: Any) -> Response: ...
    def post(self, url: str, **kwargs: Any) -> Response: ...

class AsyncClient:
    def __init__(self, *, timeout: float = ..., **kwargs: Any) -> None: ...
    async def __aenter__(self) -> "AsyncClient": ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None: ...
    async def get(self, url: str, **kwargs: Any) -> Response: ...
    async def post(self, url: str, **kwargs: Any) -> Response: ...

def get(url: str, *, timeout: float = ..., **kwargs: Any) -> Response: ...
def post(url: str, *, timeout: float = ..., **kwargs: Any) -> Response: ...
