"""Type stubs for httpx — covers only the API surface used by minirag."""

from collections.abc import Callable, Iterator
from types import TracebackType
from typing import Any

class HTTPError(Exception): ...
class ConnectError(HTTPError): ...
class ReadTimeout(HTTPError): ...
class TimeoutException(HTTPError): ...
class HTTPStatusError(HTTPError): ...

class Request:
    method: str
    url: Any
    content: bytes

class Response:
    status_code: int
    text: str
    headers: dict[str, str]

    def __init__(
        self,
        status_code: int = ...,
        *,
        json: Any = ...,
        content: Any = ...,
        text: str = ...,
        request: Request | None = ...,
        headers: dict[str, str] | None = ...,
    ) -> None: ...
    def json(self) -> Any: ...
    def iter_lines(self) -> Iterator[str]: ...
    def raise_for_status(self) -> Response: ...

class BaseTransport: ...

class MockTransport(BaseTransport):
    def __init__(self, handler: Callable[[Request], Response]) -> None: ...

class Client:
    def __init__(
        self,
        *,
        base_url: str = ...,
        timeout: float = ...,
        transport: BaseTransport | None = ...,
        **kwargs: Any,
    ) -> None: ...
    def __enter__(self) -> Client: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None: ...
    def request(self, *, method: str, url: str, json: Any = ..., **kwargs: Any) -> Response: ...
    def get(self, url: str, **kwargs: Any) -> Response: ...
    def post(self, url: str, **kwargs: Any) -> Response: ...

class AsyncClient:
    def __init__(self, *, timeout: float = ..., **kwargs: Any) -> None: ...
    async def __aenter__(self) -> "AsyncClient": ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None: ...
    async def get(self, url: str, **kwargs: Any) -> Response: ...
    async def post(self, url: str, **kwargs: Any) -> Response: ...

def get(url: str, *, timeout: float = ..., **kwargs: Any) -> Response: ...
def post(url: str, *, timeout: float = ..., **kwargs: Any) -> Response: ...
